file1= open("FileOperations.txt","a")
file1.write(" \n Am  Appending the new lines of code..")
file1.close()
file1= open("FileOperations.txt","r")
file1.seek(0,0)
#print(file1.read())
file1.close()

file1= open("FileOperations.txt","a+")
file1.write("\n Learning Python is Fun!!!")
file1.seek(0,0)
print(file1.read())
print(file1.read())
file1.close()